const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const express = require('express');
const { once } = require('node:events');
const { WebSocket } = require('ws');

const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'pi-activity-api-')));
process.env.PI_CODING_AGENT_DIR = path.join(root, 'agent');
process.env.PI_PROJECT_ROOTS = root;
process.env.PI_WEB_TOKEN = 'isolated-test-token';
const { createPiAgentGateway } = require('../server/pi-agent-routes');

test('activity and pins are protected, root-checked and do not launch workers', async t => {
    const gateway = createPiAgentGateway();
    const app = express();
    app.use(express.json());
    gateway.mount(app);
    const server = app.listen(0, '127.0.0.1');
    const wss = gateway.attachWebSocket(server);
    await once(server, 'listening');
    t.after(async () => {
        for (const socket of wss.clients) socket.terminate();
        await gateway.dispose();
        await new Promise(resolve => server.close(resolve));
        fs.rmSync(root, { recursive: true, force: true });
    });
    const url = `http://127.0.0.1:${server.address().port}/api/pi`;
    const request = (endpoint, options = {}) => fetch(`${url}${endpoint}`, {
        ...options, headers: { Authorization: 'Bearer isolated-test-token', 'Content-Type': 'application/json', ...options.headers }
    });
    assert.equal((await fetch(`${url}/activity`)).status, 401);
    assert.equal((await request('/activity', { headers: { Origin: 'http://untrusted.invalid' } })).status, 403);
    const pin = (cwd, pinned) => request('/projects/pin', { method: 'PATCH', body: JSON.stringify({ cwd, pinned }) });
    assert.equal((await pin('/etc', true)).status, 400);
    const escape = path.join(root, 'escape');
    fs.symlinkSync('/etc', escape);
    assert.equal((await pin(escape, true)).status, 400);
    assert.equal((await pin(root, 'true')).status, 400);
    assert.equal((await pin(root, true)).status, 200);
    const projects = await (await request('/projects')).json();
    assert.deepEqual(projects.pinnedProjects, [root]);
    assert.ok(projects.projects.some(project => project.cwd === root));
    assert.deepEqual((await (await request('/activity')).json()).runtimes, []);
    assert.equal(gateway.supervisor.workers.size, 0);
    const visibility = (cwd, hidden) => request('/projects/visibility', { method: 'PATCH', body: JSON.stringify({ cwd, hidden }) });
    assert.equal((await visibility('/etc', true)).status, 400);
    assert.equal((await visibility(escape, true)).status, 400);
    assert.equal((await visibility(root, 'true')).status, 400);
    assert.equal((await visibility(root, true)).status, 200);
    assert.deepEqual((await (await request('/activity')).json()).hiddenProjects, [root]);
    assert.deepEqual((await (await request('/activity')).json()).pinnedProjects, []);
    assert.ok((await (await request('/projects')).json()).projects.some(project => project.cwd === root));
    assert.ok(fs.statSync(root).isDirectory());
    assert.equal((await visibility(root, false)).status, 200);
    const alias = path.join(root, 'alias');
    fs.symlinkSync(root, alias);
    const recent = [root + '/', alias, '/etc', path.join(root, 'missing')];
    const resolvedProjects = await (await request(`/projects?recent=${encodeURIComponent(JSON.stringify(recent))}`)).json();
    assert.deepEqual(resolvedProjects.projectAliases, recent.map((input, index) => ({ input, cwd: index < 2 ? root : null })));
    assert.deepEqual(await (await request(`/projects/resolve?cwd=${encodeURIComponent(alias)}`)).json(), { cwd: root });
    assert.equal((await request('/projects/resolve?cwd=/etc')).status, 400);
    assert.equal((await request('/projects?recent=invalid-json')).status, 400);
    assert.equal((await request(`/projects?recent=${encodeURIComponent(JSON.stringify(Array(65).fill(root)))}`)).status, 400);
    const hiddenViaAlias = await (await visibility(alias, true)).json();
    assert.equal(hiddenViaAlias.cwd, root);
    assert.ok(hiddenViaAlias.hiddenProjects.includes(root));
    assert.ok(fs.statSync(root).isDirectory());
    await visibility(root, false);
    const startingTemporary = gateway.supervisor.createEphemeralWorker(root);
    assert.equal(gateway.supervisor.hasProjectRuntime(root), true);
    const temporary = await startingTemporary;
    assert.equal((await visibility(root, true)).status, 409);
    await temporary.dispose();

    const session = await gateway.store.createSession(root, 'activity smoke');
    assert.equal((await visibility(root, true)).status, 409);
    assert.ok(fs.existsSync(session.path));
    const beforeUnread = fs.readFileSync(session.path, 'utf8');
    const archive = (endpoint, cwd, archived) => request(endpoint, { method: 'PATCH', body: JSON.stringify({ cwd, archived }) });
    const threadArchive = `/sessions/${session.id}/archive`;
    assert.equal((await (await request('/status')).json()).archives, true);
    assert.equal((await fetch(`${url}/projects/archive`, { method: 'PATCH' })).status, 401);
    assert.equal((await archive('/projects/archive', '/etc', true)).status, 400);
    assert.equal((await archive('/projects/archive', escape, true)).status, 400);
    assert.equal((await archive('/projects/archive', root, 'true')).status, 400);
    assert.equal((await archive('/sessions/nonexistent/archive', root, true)).status, 400);
    assert.equal((await archive(threadArchive, '/etc', true)).status, 400);
    const prefs = new (require('../server/workspace-preferences-service').WorkspacePreferencesService)();
    prefs.writeDocument({ ...prefs.readDocument(), retainedFutureField: { untouched: true } });
    await pin(root, true);
    const a1 = await (await archive(threadArchive, alias, true)).json();
    assert.equal(a1.cwd, root);
    const a2 = await (await archive('/projects/archive', alias, true)).json();
    assert.ok(a2.archives.revision > a1.archives.revision);
    assert.deepEqual(a2.archives.projects, [root]);
    assert.deepEqual(a2.archives.sessions, [{ cwd: root, sessionId: session.id }]);
    const a3 = await (await archive('/projects/archive', root, false)).json();
    assert.deepEqual(a3.archives.projects, []);
    assert.deepEqual(a3.archives.sessions, a2.archives.sessions, 'project restore preserves individual thread archive');
    assert.deepEqual(new (require('../server/workspace-preferences-service').WorkspacePreferencesService)().getArchives(), a3.archives);
    assert.deepEqual(prefs.readDocument().retainedFutureField, { untouched: true });
    assert.deepEqual(prefs.getPinnedProjects(), [root]);
    assert.equal((await (await request(`/sessions?cwd=${encodeURIComponent(root)}`)).json()).sessions.length, 1);
    assert.equal(fs.readFileSync(session.path, 'utf8'), beforeUnread);
    assert.equal(gateway.supervisor.workers.size, 0, 'archiving starts no worker');
    assert.deepEqual((await (await request('/activity')).json()).archives, a3.archives);
    await archive(threadArchive, root, false);
    const unread = () => request(`/sessions/${session.id}/unread`, { method: 'PATCH', body: JSON.stringify({ cwd: root }) });
    assert.equal((await fetch(`${url}/sessions/${session.id}/unread`, { method: 'PATCH' })).status, 401);
    assert.equal((await request(`/sessions/${session.id}/unread`, { method: 'PATCH', body: JSON.stringify({ cwd: '/etc' }) })).status, 400);
    assert.equal((await request('/sessions/nonexistent/unread', { method: 'PATCH', body: JSON.stringify({ cwd: root }) })).status, 400);
    const firstManual = (await (await unread()).json()).notice;
    const secondManual = (await (await unread()).json()).notice;
    assert.equal(secondManual.manual, true);
    assert.notEqual(firstManual.completionId, secondManual.completionId);
    assert.equal(gateway.supervisor.workers.size, 0, 'mark unread does not launch a worker');
    assert.equal(fs.readFileSync(session.path, 'utf8'), beforeUnread, 'mark unread does not write session history');
    await request(`/sessions/${session.id}/read`, { method: 'PATCH', body: JSON.stringify({ cwd: root, completionId: firstManual.completionId }) });
    assert.deepEqual((await (await request('/activity')).json()).replyNotices, [secondManual]);
    const socket = new WebSocket(`${url.replace('http:', 'ws:')}/ws`);
    await once(socket, 'open');
    const snapshot = once(socket, 'message');
    socket.send(JSON.stringify({ id: 'test-open', type: 'open_session', cwd: root, sessionId: session.id, token: 'isolated-test-token' }));
    const opened = JSON.parse((await snapshot)[0]);
    assert.equal(opened.success, true);
    assert.equal(opened.data.session.id, session.id);
    assert.deepEqual(opened.data.completion, secondManual, 'opening the thread captures the manual read token');
    const worker = gateway.supervisor.getActiveWorker(session.path);
    worker.client.emit('event', { type: 'agent_start' });
    const busyBeforeArchive = gateway.supervisor.getActivity();
    await archive(threadArchive, root, true);
    await archive('/projects/archive', root, true);
    assert.deepEqual(gateway.supervisor.getActivity(), busyBeforeArchive, 'archiving does not stop a running worker');
    assert.equal(gateway.supervisor.workers.size, 1);
    await archive('/projects/archive', root, false);
    await archive(threadArchive, root, false);
    const serverClosed = once([...wss.clients][0], 'close');
    const clientClosed = once(socket, 'close');
    socket.close();
    await Promise.all([clientClosed, serverClosed]);
    assert.equal(worker.subscribers.size, 0);
    const summary = await (await request('/activity')).json();
    assert.deepEqual(summary.runtimes, [{ cwd: root, sessionId: session.id, titleGenerating: false, phase: 'running', busy: true }]);
    assert.equal(worker.canEvict(Date.now() + 100000, 1), false);
    worker.client.emit('event', { type: 'agent_settled' });
    worker.client.emit('event', { type: 'compaction_start' });
    assert.equal(worker.canEvict(Date.now() + 100000, 1), false);
    worker.client.emit('event', { type: 'compaction_end' });
    assert.equal(worker.canEvict(Date.now() + 100000, 1), true);

    worker.client.emit('event', { type: 'extension_ui_request', id: 'pending-confirm', method: 'confirm', title: 'Private confirmation' });
    const waiting = await (await request('/activity')).json();
    assert.equal(waiting.runtimes[0].phase, 'waiting');
    assert.equal(JSON.stringify(waiting).includes('Private confirmation'), false);
    assert.equal(worker.canEvict(Date.now() + 100000, 1), false);
    const reconnect = new WebSocket(`${url.replace('http:', 'ws:')}/ws`);
    await once(reconnect, 'open');
    const replay = once(reconnect, 'message');
    reconnect.send(JSON.stringify({ id: 'replay', type: 'open_session', cwd: root, sessionId: session.id, token: 'isolated-test-token' }));
    assert.equal(JSON.parse((await replay)[0]).data.pendingUi[0].id, 'pending-confirm');
    const sent = [];
    const originalSend = worker.client.send.bind(worker.client);
    worker.client.send = record => sent.push(record);
    const resolved = once(reconnect, 'message');
    reconnect.send(JSON.stringify({ type: 'extension_ui_response', id: 'pending-confirm', confirmed: true }));
    assert.equal(JSON.parse((await resolved)[0]).type, 'gateway_ui_resolved');
    assert.equal(worker.send({ type: 'extension_ui_response', id: 'pending-confirm', confirmed: false }), false);
    assert.equal(sent.length, 1);
    assert.equal(worker.getPendingUi().length, 0);
    worker.client.send = originalSend;
    worker.client.emit('event', { type: 'extension_ui_request', id: 'timed', method: 'input', timeout: 15 });
    await new Promise(resolve => setTimeout(resolve, 35));
    assert.equal(worker.getPendingUi().length, 0);
    worker.client.emit('event', { type: 'agent_start' });
    worker.client.emit('event', { type: 'extension_ui_request', id: 'aborted-dialog', method: 'confirm', timeout: 0 });
    await new Promise(resolve => setTimeout(resolve, 10));
    assert.equal(worker.getPendingUi().length, 1);
    worker.client.emit('event', { type: 'agent_settled' });
    assert.equal(worker.getPendingUi().length, 0);
    reconnect.close();
    await once(reconnect, 'close');

    worker.client.emit('event', { type: 'agent_start' });
    worker.client.emit('event', { type: 'message_end', message: { role: 'assistant', stopReason: 'stop', content: 'Done' } });
    worker.client.emit('event', { type: 'agent_settled' });
    const notice = (await (await request('/activity')).json()).replyNotices[0];
    assert.equal(notice.sessionId, session.id);
    assert.ok(notice.completionId);
    assert.equal(notice.manual, undefined, 'a new completion replaces the manual notice');
    assert.equal((await request(`/sessions/${session.id}/read`, { method: 'PATCH', body: JSON.stringify({ cwd: '/etc', completionId: notice.completionId }) })).status, 400);
    await request(`/sessions/${session.id}/read`, { method: 'PATCH', body: JSON.stringify({ cwd: root, completionId: 'stale' }) });
    assert.equal((await (await request('/activity')).json()).replyNotices.length, 1);
    await request(`/sessions/${session.id}/read`, { method: 'PATCH', body: JSON.stringify({ cwd: root, completionId: notice.completionId }) });
    assert.deepEqual((await (await request('/activity')).json()).replyNotices, []);
    await gateway.supervisor.stopSession(session.path);
    assert.deepEqual((await (await request('/activity')).json()).runtimes, []);
});
