const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const { once } = require('node:events');
const { WebSocket } = require('ws');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-composer-'));
process.env.PI_CODING_AGENT_DIR = path.join(root, 'agent');
process.env.PI_PROJECT_ROOTS = root;
process.env.PI_WEB_DEFERRED_FILE = path.join(root, 'deferred.json');
process.env.PI_OFFLINE = '1';
process.env.PI_WEB_TOKEN = 'composer-fixture-token';
const { PiSessionStore } = require('../server/pi-session-store');
const { PiComposerService, BUILTINS } = require('../server/pi-composer-service');
const store = new PiSessionStore(), service = new PiComposerService(store);
const cwd = path.join(root, 'project'); fs.mkdirSync(cwd);
test.after(() => fs.rmSync(root, { recursive: true, force: true }));

test('native prompt files: scopes, lossless Markdown, revisions, backups and path boundaries', async () => {
    const input = { cwd, scope: 'user', name: 'review', content: '---\ndescription: Review\ncustom: preserve\n---\nReview $1; ${2:-default}.', expectedRevision: null };
    const saved = await service.save(input);
    require('./private-file-helper.cjs').assertPrivateFile(path.join(root, 'agent/prompts/review.md'));
    assert.equal((await service.get(input)).content, input.content);
    assert.equal((await service.list(cwd)).templates[0].description, 'Review');
    await assert.rejects(service.save(input), /修改/);
    await service.save({ ...input, content: 'new $@', expectedRevision: saved.revision });
    assert.equal(fs.readdirSync(path.join(root, 'agent/prompts/.web-backups')).length, 1);
    fs.writeFileSync(path.join(root, 'agent/prompts/review.md'), 'changed in terminal');
    await assert.rejects(service.save({ ...input, expectedRevision: saved.revision }), /修改/);
    const current = await service.get(input);
    await service.save({ ...input, expectedRevision: current.revision }, true);
    assert.equal(fs.existsSync(path.join(root, 'agent/prompts/review.md')), false);
    assert.equal(fs.readdirSync(path.join(root, 'agent/prompts/.web-backups')).length, 2);
    await service.save({ ...input, scope: 'project' });
    assert.equal((await service.list(cwd)).templates[0].scope, 'project');
    await assert.rejects(service.save({ ...input, name: '../auth' }), /模板名/);
    await assert.rejects(service.save({ ...input, name: 'model' }), /冲突/);
    await assert.rejects(service.list('/etc'));
    await assert.rejects(service.files('/etc', 'passwd'));
    fs.symlinkSync(path.join(cwd, '.pi/prompts/review.md'), path.join(root, 'agent/prompts/link.md'));
    await assert.rejects(service.get({ ...input, name: 'link' }), /普通/);
    const linked = path.join(root, 'linked'); fs.mkdirSync(linked); fs.symlinkSync(path.join(cwd, '.pi'), path.join(linked, '.pi'));
    await assert.rejects(service.save({ ...input, cwd: linked, scope: 'project' }), /符号链接/);
    await assert.rejects(service.save({ ...input, content: 'x'.repeat(65537) }), /64 KiB/);
});

test('project search: fuzzy paths and spaces; ignored files, credentials and escaping symlinks stay out', async () => {
    fs.mkdirSync(path.join(cwd, '.git')); fs.mkdirSync(path.join(cwd, 'src'));
    fs.writeFileSync(path.join(cwd, '.gitignore'), 'ignored.txt\n');
    for (const file of ['src/button click.js', 'src/组件.ts', 'src/😀.js', 'ignored.txt', '.env', '.env.local', 'auth.json']) fs.writeFileSync(path.join(cwd, file), 'fixture');
    fs.symlinkSync('/etc/passwd', path.join(cwd, 'escape.txt'));
    const result = await service.files(cwd, 'btncl'); assert.deepEqual(result.files, [{ path: 'src/button click.js' }]);
    assert.deepEqual((await service.files(cwd, '😀')).files, [{ path: 'src/😀.js' }]);
    const all = await service.files(cwd, '');
    assert.ok(all.files.some(f => f.path === 'src/组件.ts'));
    assert.ok(!all.files.some(f => /escape|ignored|\.env|auth\.json/.test(f.path)));
    await assert.rejects(service.files(cwd, '\0'));
    service.searches = 2; await assert.rejects(service.files(cwd, 'x'), /正在进行/); service.searches = 0;
});

test('actual Pi RPC reloads templates without session navigation; expands native arguments and blocks reload while running', { timeout: 90000 }, async t => {
    let hold = false; const requests = [], held = new Set();
    const provider = http.createServer(async (req, res) => {
        let body = ''; for await (const chunk of req) body += chunk;
        requests.push(JSON.parse(body));
        if (hold) { held.add(res); res.on('close', () => held.delete(res)); return; }
        res.writeHead(200, { 'Content-Type': 'text/event-stream' });
        res.write('data: ' + JSON.stringify({ id: 'fixture', object: 'chat.completion.chunk', model: 'fixture', choices: [{ index: 0, delta: { role: 'assistant', content: 'Done' }, finish_reason: null }] }) + '\n\n');
        res.end('data: ' + JSON.stringify({ id: 'fixture', object: 'chat.completion.chunk', model: 'fixture', choices: [{ index: 0, delta: {}, finish_reason: 'stop' }], usage: { prompt_tokens: 20, completion_tokens: 2, total_tokens: 22 } }) + '\n\ndata: [DONE]\n\n');
    });
    provider.listen(0, '127.0.0.1'); await once(provider, 'listening');
    fs.writeFileSync(path.join(root, 'agent/models.json'), JSON.stringify({ providers: { fixture: { baseUrl: `http://127.0.0.1:${provider.address().port}/v1`, api: 'openai-completions', apiKey: 'fixture', models: [{ id: 'fixture', input: ['text'], contextWindow: 32000, maxTokens: 1000 }] } } }));
    fs.writeFileSync(path.join(root, 'agent/settings.json'), JSON.stringify({ defaultProvider: 'fixture', defaultModel: 'fixture', compaction: { enabled: false } }));
    const { createPiAgentGateway } = require('../server/pi-agent-routes');
    const gateway = createPiAgentGateway({ deferredFilePath: process.env.PI_WEB_DEFERRED_FILE });
    // This fixture exercises composer requests without background title model calls.
    gateway.titles.saveSettings({ enabled: false });
    const app = require('express')(); app.use(require('express').json()); gateway.mount(app);
    const server = http.createServer(app); gateway.attachWebSocket(server); server.listen(0, '127.0.0.1'); await once(server, 'listening');
    let socket;
    t.after(async () => { socket?.terminate(); held.forEach(res => res.destroy()); await gateway.dispose(); server.closeAllConnections(); provider.closeAllConnections(); await Promise.all([new Promise(r => server.close(r)), new Promise(r => provider.close(r))]); });
    const origin = `http://127.0.0.1:${server.address().port}`;
    const endpoint = `${origin}/api/pi/composer/catalog?cwd=${encodeURIComponent(cwd)}`;
    assert.equal((await fetch(endpoint)).status, 401);
    assert.equal((await fetch(endpoint, { headers: { Authorization: 'Bearer composer-fixture-token', Origin: 'http://untrusted.invalid' } })).status, 403);
    const catalog = await fetch(endpoint, { headers: { Authorization: 'Bearer composer-fixture-token' } });
    assert.equal(catalog.headers.get('cache-control'), 'no-store'); assert.equal(catalog.status, 200);
    assert.ok(BUILTINS.find(c => c.name === 'share' && !c.available));
    const session = await gateway.store.createSession(cwd, 'Composer fixture');
    socket = new WebSocket(origin.replace('http:', 'ws:') + '/api/pi/ws'); await once(socket, 'open');
    let id = 0; const pending = new Map(), events = [];
    socket.on('message', raw => { const e = JSON.parse(raw); const p = e.type === 'response' && pending.get(e.id); if (p) { clearTimeout(p.timer); pending.delete(e.id); e.success ? p.resolve(e.data) : p.reject(new Error(e.error)); } else events.push(e); });
    const call = (type, data = {}) => new Promise((resolve, reject) => { const key = String(++id); const timer = setTimeout(() => { pending.delete(key); reject(Error(type + ' timed out')); }, 20000); pending.set(key, { resolve, reject, timer }); socket.send(JSON.stringify({ type, id: key, ...data })); });
    const waitFor = async fn => { for (let i = 0; i < 400; i++) { if (fn()) return; await new Promise(r => setTimeout(r, 20)); } throw Error('event timeout'); };
    await call('open_session', { cwd, sessionId: session.id, token: 'composer-fixture-token' });
    const original = fs.readFileSync(session.path, 'utf8');
    await service.save({ cwd, scope: 'user', name: 'native-review', content: '---\ndescription: Native test\nargument-hint: "<file> [notes]"\n---\nInspect $1; notes: ${2:-default}; all: $@', expectedRevision: null });
    assert.ok(!(await call('get_commands')).commands.some(c => c.name === 'native-review'));
    const loaded = await call('reload_resources');
    assert.ok(loaded.commands.some(c => c.name === 'native-review' && c.source === 'prompt'));
    assert.equal(fs.readFileSync(session.path, 'utf8'), original, 'reload must not write a parallel history or navigate the session');
    assert.equal(requests.length, 0, 'resource reload does not call a model');
    assert.ok(events.some(e => e.type === 'gateway_commands'));
    await call('prompt', { message: `/native-review 'src/button click.js' 'a'"'"'b "中文" $1'` });
    await waitFor(() => events.some(e => e.type === 'agent_settled'));
    const user = (await call('get_messages')).messages.find(m => m.role === 'user');
    const text = typeof user.content === 'string' ? user.content : user.content.filter(c => c.type === 'text').map(c => c.text).join('\n');
    assert.equal(text, `Inspect src/button click.js; notes: a'b "中文" $1; all: src/button click.js a'b "中文" $1`);
    hold = true; await call('prompt', { message: 'Keep running' }); await waitFor(() => held.size);
    await assert.rejects(call('reload_resources'), /运行|空闲/);
    await call('steer', { message: '/native-review next.js' });
    assert.match((await call('get_state')).webControls.queue.steering[0], /Inspect next.js; notes: default/);
    await call('stop_and_recover');
    assert.equal(gateway.supervisor.workers.size, 1);
    const raw = fs.readFileSync(session.path, 'utf8'); assert.doesNotMatch(raw, /pi5-web-navigate|reload-v1/);
});
