const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const http = require('node:http');
const { once } = require('node:events');
const { WebSocket } = require('ws');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-history-'));
process.env.PI_CODING_AGENT_DIR = path.join(root, 'agent'); process.env.PI_PROJECT_ROOTS = root;
process.env.PI_WEB_DEFERRED_FILE = path.join(root, 'deferred.json'); process.env.PI_OFFLINE = '1'; process.env.PI_WEB_TOKEN = 'history-fixture';
const { searchHistory, previewHistory, setHistoryBookmark, validateHistoryRequest } = require('../server/pi-history-model');
const assistant = text => ({ role: 'assistant', content: [{ type: 'text', text }], timestamp: Date.now(), stopReason: 'stop', provider: 'fixture', model: 'fixture', api: 'openai-completions', usage: { input: 10, output: 3, cacheRead: 0, cacheWrite: 0, totalTokens: 13, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } } });
const question = text => ({ role: 'user', content: text, timestamp: Date.now() });
test.after(() => fs.rmSync(root, { recursive: true, force: true }));
test('history searches native pre-compaction records and other branches, with safe projections and pagination', async () => {
    const { SessionManager } = await import('@earendil-works/pi-coding-agent');
    const sm = SessionManager.inMemory(root);
    const old = sm.appendMessage(question('早期决策 [a+b] 中文\u2028分隔'));
    const first = sm.appendMessage(assistant('已验证方案'));
    const retained = sm.appendMessage(question('后续问题'));
    const long = sm.appendMessage(assistant('x'.repeat(17000) + 'deep-needle'));
    sm.appendCompaction('当前摘要', retained, 50000);
    const compactLeaf = sm.getLeafId();
    assert.ok(searchHistory(sm, { q: '[a+b]' }).results.some(r => r.entryId === old));
    assert.ok(!JSON.stringify(sm.buildSessionContext().messages).includes('早期决策'));
    const result = searchHistory(sm, { q: 'deep-needle' }).results[0]; assert.equal(result.entryId, long); assert.equal(result.matchOffset, 17000);
    assert.match(previewHistory(sm, { entryId: long, offset: 16000 }).text, /deep-needle/);
    const emoji = sm.appendMessage(assistant('a'.repeat(15999) + '😀end'));
    const head = previewHistory(sm, { entryId: emoji });
    assert.equal(head.nextOffset, 15999); assert.equal(head.text.length, 15999);
    assert.equal(previewHistory(sm, { entryId: emoji, offset: head.nextOffset }).text, '😀end');
    const before = JSON.stringify(sm.getEntries()), beforeLeaf = sm.getLeafId(); searchHistory(sm, {}); previewHistory(sm, { entryId: old }); assert.equal(JSON.stringify(sm.getEntries()), before); assert.equal(sm.getLeafId(), beforeLeaf);
    assert.equal(sm.getEntry(compactLeaf).type, 'compaction');
    sm.branch(first); sm.appendMessage(question('其他路线'));
    assert.equal(searchHistory(sm, { q: 'deep-needle' }).total, 0);
    assert.equal(searchHistory(sm, { q: 'deep-needle', scope: 'all' }).results[0].inCurrentBranch, false);
    const tool = sm.appendMessage({ ...assistant('混合正文'), content: [{ type: 'text', text: '混合正文' }, { type: 'toolCall', id: 'call1', name: 'edit', arguments: { path: 'src/目标.js', edits: [{ oldText: 'old', newText: 'new' }] } }, { type: 'thinking', thinking: 'PRIVATE_THINKING' }] });
    sm.appendMessage({ role: 'toolResult', toolCallId: 'call1', toolName: 'edit', content: [{ type: 'text', text: '工具返回 EACCES' }], details: { private: 'PRIVATE_DETAILS' }, timestamp: Date.now() });
    const hidden = sm.appendCustomMessageEntry('private', 'PRIVATE_CONTEXT', false);
    assert.equal(searchHistory(sm, { q: '目标.js', filter: 'tool' }).results[0].entryId, tool);
    for (const q of ['PRIVATE_THINKING', 'PRIVATE_DETAILS', 'PRIVATE_CONTEXT']) assert.equal(searchHistory(sm, { q, scope: 'all' }).total, 0);
    assert.throws(() => previewHistory(sm, { entryId: hidden }), /不存在/);
    for (let i = 0; i < 65; i++) sm.appendMessage(question(`page item ${i}`));
    const page1 = searchHistory(sm, { q: 'page item' }); assert.equal(page1.total, 65); assert.equal(page1.results.length, 30);
    const page2 = searchHistory(sm, { q: 'page item', offset: 30, revision: page1.revision });
    assert.ok(!page2.results.some(r => page1.results.some(p => p.entryId === r.entryId)));
    sm.appendMessage(question('new history'));
    assert.throws(() => searchHistory(sm, { q: 'page item', offset: 30, revision: page1.revision }), /更新/);
});
test('search and preview share tree reply stages before filtering, bookmarks and pagination', async () => {
    const { SessionManager } = await import('@earendil-works/pi-coding-agent');
    const { sessionTree } = require('../server/pi-session-tree');
    const sm = SessionManager.inMemory(root);
    sm.appendMessage(question('question'));
    const progress = sm.appendMessage(assistant('matching progress'));
    const final = sm.appendMessage(assistant('different completed answer'));
    sm.appendMessage(question('next question'));
    const tail = sm.appendMessage(assistant('matching current tail'));
    const before = JSON.stringify(sm.getEntries());
    const stages = new Map(sessionTree(sm, {}, { settled: true }).rows.map(r => [r.entryId, r.replyStage]));
    for (const r of searchHistory(sm, { filter: 'assistant' }, { settled: true }).results) assert.equal(r.replyStage, stages.get(r.entryId));
    assert.equal(searchHistory(sm, { q: 'matching progress', filter: 'assistant' }, { settled: true }).results[0].replyStage, 'progress', 'non-matching continuation still determines the stage');
    assert.equal(previewHistory(sm, { entryId: progress }, { settled: true }).replyStage, 'progress');
    assert.equal(previewHistory(sm, { entryId: final }, { settled: false }).replyStage, 'final');
    assert.equal(previewHistory(sm, { entryId: tail }, { settled: false }).replyStage, 'pending');
    assert.equal(previewHistory(sm, { entryId: tail }, { settled: true }).replyStage, 'final');
    assert.equal(JSON.stringify(sm.getEntries()), before);
    sm.appendLabelChange(progress, 'marked');
    for (let i = 0; i < 35; i++) { sm.appendMessage(question(`later ${i}`)); sm.appendMessage(assistant(`later answer ${i}`)); }
    assert.equal(searchHistory(sm, { bookmarked: true }, { settled: true }).results[0].replyStage, 'progress');
    const page = searchHistory(sm, { filter: 'assistant' }, { settled: true });
    const next = searchHistory(sm, { filter: 'assistant', offset: 30, revision: page.revision }, { settled: true });
    assert.equal(next.results.find(r => r.entryId === progress).replyStage, 'progress');
});
test('native labels add, rename and remove without changing message ancestry; stale writes and unsupported entries reject', async () => {
    const { SessionManager } = await import('@earendil-works/pi-coding-agent'); const sm = SessionManager.inMemory(root);
    const target = sm.appendMessage(question('bookmark target'));
    assert.throws(() => setHistoryBookmark(sm, { entryId: target, label: 'x', expectedBookmarkRevision: 'none' }, sm.appendLabelChange.bind(sm)), /首条/);
    sm.appendMessage(assistant('done'));
    const ancestry = sm.getBranch().filter(e => e.type === 'message').map(e => e.id), leaf = sm.getLeafId();
    const set = input => setHistoryBookmark(sm, { entryId: target, ...input }, sm.appendLabelChange.bind(sm));
    const a = set({ label: '已验证方案', expectedBookmarkRevision: 'none' }); assert.notEqual(sm.getLeafId(), leaf);
    assert.deepEqual(sm.getBranch().filter(e => e.type === 'message').map(e => e.id), ancestry);
    assert.equal(searchHistory(sm, { q: '已验证方案', bookmarked: true }).results[0].entryId, target);
    assert.throws(() => set({ label: '旧页面覆盖', expectedBookmarkRevision: 'none' }), /其他页面/);
    const b = set({ label: '部署前', expectedBookmarkRevision: a.bookmarkRevision });
    set({ label: '', expectedBookmarkRevision: b.bookmarkRevision });
    assert.equal(searchHistory(sm, { bookmarked: true }).total, 0); assert.ok(sm.getEntry(target));
    assert.throws(() => validateHistoryRequest('search', { q: '\0' }));
    assert.throws(() => validateHistoryRequest('bookmark', { entryId: target, label: 'x'.repeat(81), expectedBookmarkRevision: 'none' }));
    assert.throws(() => validateHistoryRequest('preview', { entryId: '../file' }));
});
test('gateway history: actual Pi labels persist during streaming, two clients conflict safely, private results never broadcast', { timeout: 90000 }, async t => {
    let requests = 0; const held = new Set();
    const provider = http.createServer(async (req, res) => { for await (const _ of req) {} requests++; held.add(res); res.on('close', () => held.delete(res)); });
    provider.listen(0, '127.0.0.1'); await once(provider, 'listening');
    fs.mkdirSync(process.env.PI_CODING_AGENT_DIR, { recursive: true });
    fs.writeFileSync(path.join(process.env.PI_CODING_AGENT_DIR, 'models.json'), JSON.stringify({ providers: { fixture: { baseUrl: `http://127.0.0.1:${provider.address().port}/v1`, api: 'openai-completions', apiKey: 'fixture', models: [{ id: 'fixture', input: ['text'], contextWindow: 32000, maxTokens: 1000 }] } } }));
    fs.writeFileSync(path.join(process.env.PI_CODING_AGENT_DIR, 'settings.json'), JSON.stringify({ defaultProvider: 'fixture', defaultModel: 'fixture', compaction: { enabled: false } }));
    const { createPiAgentGateway } = require('../server/pi-agent-routes'); const gateway = createPiAgentGateway({ deferredFilePath: process.env.PI_WEB_DEFERRED_FILE });
    const app = require('express')(); app.use(require('express').json()); gateway.mount(app); const server = http.createServer(app); gateway.attachWebSocket(server); server.listen(0, '127.0.0.1'); await once(server, 'listening');
    const clients = [];
    t.after(async () => { clients.forEach(c => c.socket.terminate()); held.forEach(r => r.destroy()); await gateway.dispose(); server.closeAllConnections(); provider.closeAllConnections(); await Promise.all([new Promise(r => server.close(r)), new Promise(r => provider.close(r))]); });
    const session = await gateway.store.createSession(root, 'History fixture');
    const { SessionManager } = await import('@earendil-works/pi-coding-agent'); const seed = SessionManager.open(session.path);
    const target = seed.appendMessage(question('old decision 中文\u2029tail')); const responseEntry = seed.appendMessage(assistant('original response'));
    const connect = async () => {
        const socket = new WebSocket(`ws://127.0.0.1:${server.address().port}/api/pi/ws`); await once(socket, 'open');
        const pending = new Map(), events = []; let next = 0;
        socket.on('message', raw => { const e = JSON.parse(raw), p = e.type === 'response' && pending.get(e.id); if (p) { pending.delete(e.id); clearTimeout(p.timer); e.success ? p.resolve(e.data) : p.reject(Error(e.error)); } else events.push(e); });
        const call = (type, input = {}) => new Promise((resolve, reject) => { const id = String(++next); const timer = setTimeout(() => { pending.delete(id); reject(Error(`timeout ${type}`)); }, 40000); pending.set(id, { resolve, reject, timer }); socket.send(JSON.stringify({ type, id, ...input })); });
        const client = { socket, call, events }; clients.push(client); await call('open_session', { cwd: root, sessionId: session.id, token: 'history-fixture' }); return client;
    };
    const a = await connect(), b = await connect();
    // Opening the native runtime may append its initial thinking level. Measure reads after startup.
    const original = fs.readFileSync(session.path, 'utf8');
    const list = await a.call('search_history', { q: 'decision' }); assert.equal(list.results[0].entryId, target);
    const preview = await a.call('get_history_entry', { entryId: target }); assert.match(preview.text, /中文\u2029tail/);
    assert.equal(fs.readFileSync(session.path, 'utf8'), original, 'search and preview never write history'); assert.equal(requests, 0);
    assert.equal((await a.call('get_history_entry', { entryId: responseEntry })).replyStage, 'final');
    assert.equal((await a.call('search_history', { q: 'original response' })).results[0].replyStage, 'final');
    await a.call('prompt', { message: 'hold this run' });
    for (let i = 0; i < 300 && !held.size; i++) await new Promise(r => setTimeout(r, 20)); assert.equal(held.size, 1);
    const race = await Promise.allSettled([a.call('set_history_bookmark', { entryId: target, label: 'A', expectedBookmarkRevision: preview.bookmarkRevision }), b.call('set_history_bookmark', { entryId: target, label: 'B', expectedBookmarkRevision: preview.bookmarkRevision })]);
    assert.equal(race.filter(r => r.status === 'fulfilled').length, 1); assert.equal(requests, 1);
    assert.equal((await a.call('get_state')).isStreaming, true, 'adding a bookmark does not stop the active task');
    assert.ok(b.events.some(e => e.type === 'gateway_history_changed'));
    const saved = await b.call('get_history_entry', { entryId: target }); assert.ok(['A', 'B'].includes(saved.label));
    assert.ok(fs.readFileSync(session.path, 'utf8').includes('"type":"label"'));
    const worker = gateway.supervisor.getActiveWorker(session.path);
    worker._handleEvent({ type: 'extension_ui_request', method: 'notify', message: JSON.stringify({ pi5History: 'unknown-old-response', success: true, data: { text: 'PRIVATE_LATE' } }) });
    assert.ok(!a.events.some(e => e.type === 'extension_ui_request' && /pi5History|PRIVATE_LATE/.test(e.message || '')));
    await a.call('stop_and_recover'); a.socket.close(); const c = await connect();
    assert.equal((await c.call('get_history_entry', { entryId: target })).label, saved.label);
    await c.call('set_history_bookmark', { entryId: target, label: '', expectedBookmarkRevision: saved.bookmarkRevision });
    assert.equal((await b.call('search_history', { bookmarked: true })).total, 0);
    assert.equal(gateway.supervisor.workers.size, 1);
    const originalRequest = worker.client.request.bind(worker.client); let attempts = 0;
    worker.client.request = async (type, payload, ...rest) => {
        if (type === 'prompt' && payload.message.includes('"kind":"bookmark"')) { attempts++; throw Object.assign(Error('fixture timeout'), { code: 'RPC_TIMEOUT' }); }
        return originalRequest(type, payload, ...rest);
    };
    const latest = await c.call('get_history_entry', { entryId: target });
    const update = { entryId: target, label: 'uncertain', expectedBookmarkRevision: latest.bookmarkRevision };
    await assert.rejects(worker.historyRequest('bookmark', update), /timeout/);
    assert.ok(worker.historyWriting); assert.equal(worker.canEvict(Date.now() + 100000, 1), false);
    await assert.rejects(worker.historyRequest('bookmark', update), /尚未结束/);
    await assert.rejects(worker.request('compact'), /保存书签/);
    assert.equal((await worker.historyRequest('preview', { entryId: target })).label, '');
    const waiting = [...worker.historyResults].find(([, value]) => value.writing);
    worker._handleEvent({ type: 'extension_ui_request', method: 'notify', message: JSON.stringify({ pi5History: waiting[0], success: false, error: 'late authoritative rejection' }) });
    assert.equal(worker.historyWriting, null); assert.equal(attempts, 1);
    worker.client.request = originalRequest;
    assert.doesNotMatch(fs.readFileSync(session.path, 'utf8'), /pi5-web-navigate|pi5History/);
});
