const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),http=require('node:http');
const {once}=require('node:events');const {WebSocket}=require('ws');
const root=fs.realpathSync.native(fs.mkdtempSync(path.join(os.tmpdir(),'pi-model-onboarding-')));
process.env.PI_CODING_AGENT_DIR=path.join(root,'agent');process.env.PI_PROJECT_ROOTS=root;process.env.PI_WEB_DEFERRED_FILE=path.join(root,'deferred.json');process.env.PI_OFFLINE='1';delete process.env.PI_WEB_APPROVE_PROJECTS;
test.after(()=>fs.rmSync(root,{recursive:true,force:true}));
const wait=async f=>{const end=Date.now()+15000;while(!f()){if(Date.now()>end)throw Error('fixture timeout');await new Promise(r=>setTimeout(r,20))}};
test('an already-open empty runtime discovers later credentials in place without sending or selecting a model', {timeout:60000}, async t=>{
 const {createPiAgentGateway}=require('../server/pi-agent-routes');const {PiSettingsService}=require('../server/pi-settings-service');let calls=0;
 const provider=http.createServer(async(req,res)=>{assert.equal(req.headers.authorization,'Bearer private-fixture-key');for await(const _ of req){}calls++;res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',content:'CATALOG_OK'},finish_reason:'stop'}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}})+'\n\ndata: [DONE]\n\n')});provider.listen(0,'127.0.0.1');await once(provider,'listening');
 const gateway=createPiAgentGateway();const app=require('express')();app.use(require('express').json());gateway.mount(app);const server=http.createServer(app);gateway.attachWebSocket(server);server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port,sockets=[];
 t.after(async()=>{for(const s of sockets)s.terminate();await gateway.dispose();server.closeAllConnections();await new Promise(r=>server.close(r));provider.closeAllConnections();await new Promise(r=>provider.close(r))});
 const session=await gateway.store.createSession(root,'Empty first runtime');
 async function connect(){const ws=new WebSocket(base.replace('http:','ws:')+'/api/pi/ws',{origin:base});sockets.push(ws);const pending=new Map(),events=[];let seq=0;ws.on('message',raw=>{const e=JSON.parse(raw);if(e.type==='response'&&pending.has(e.id)){const p=pending.get(e.id);pending.delete(e.id);clearTimeout(p.timer);e.success?p.resolve(e.data):p.reject(Object.assign(Error(e.error),{code:e.errorCode}))}else events.push(e)});await once(ws,'open');const call=(type,data={})=>new Promise((resolve,reject)=>{const id=String(++seq),timer=setTimeout(()=>reject(Error('timeout '+type)),15000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,type,...data}))});return {call,events,snapshot:await call('open_session',{cwd:root,sessionId:session.id})}}
 const main=await connect(),other=await connect();assert.equal(main.snapshot.models.models.length,0);const before=fs.readFileSync(session.path);const initial=(await main.call('get_state')).model;
 await assert.rejects(main.call('prompt',{message:'MUST_NOT_BE_ACCEPTED'}),e=>e.code==='MODEL_AUTH_REQUIRED'&&!e.message.includes('node_modules')&&e.message.includes('供应商与模型'));assert.deepEqual(fs.readFileSync(session.path),before);
 const settings=new PiSettingsService({cwd:root});await settings.upsertCustomProvider({id:'catalog-fixture',baseUrl:`http://127.0.0.1:${provider.address().port}/v1`,api:'openai-completions',authHeader:true});await settings.upsertCustomModel('catalog-fixture',{id:'fixture',name:'Fixture',contextWindow:32000,maxTokens:1000,imageInput:false});await settings.saveApiKey('catalog-fixture','private-fixture-key');
 assert.equal((await main.call('get_available_models')).models.length,0,'old native snapshot reproduces the bug');
 const [fresh,shared]=await Promise.all([main.call('refresh_models'),other.call('refresh_models')]);assert.ok(fresh.models.some(m=>m.provider==='catalog-fixture'));assert.deepEqual(shared,fresh);assert.equal(calls,0);assert.equal(gateway.supervisor.workers.size,1);assert.deepEqual((await main.call('get_state')).model,initial,'refresh does not select or replace the model');assert.deepEqual(fs.readFileSync(session.path),before,'private command is not conversation history');assert.ok(main.events.some(e=>e.type==='gateway_models'));assert.doesNotMatch(JSON.stringify([...main.events,...other.events,fresh]),/private-fixture-key|pi5Models|pi5-web-navigate/);
 await main.call('set_model',{provider:'catalog-fixture',modelId:'fixture'});await main.call('prompt',{message:'Only a synthetic endpoint receives this'});await wait(()=>main.events.some(e=>e.type==='agent_settled'));assert.equal(calls,1);
 const worker=gateway.supervisor.getActiveWorker(session.path);worker.client.emit('event',{type:'agent_start'});await assert.rejects(main.call('refresh_models'),{code:'SESSION_BUSY'});worker.client.emit('event',{type:'agent_settled'});
 await settings.logout('catalog-fixture');assert.equal((await main.call('refresh_models')).models.length,0,'logout removes availability from the same worker');assert.equal(calls,1);
});
test('catalog responses remain private and an uncertain refresh closes the reserved idle worker',async()=>{
 const {PiModelCatalog}=require('../server/pi-model-catalog');let disposed=false,reserved=false;const events=[];const worker={navigationToken:'fixture',_broadcast:e=>events.push(e),async dispose(){assert.equal(reserved,true);disposed=true},async exclusive(fn){reserved=true;try{return await fn()}finally{reserved=false}},client:{async request(type){if(type==='get_commands')return {commands:[{name:'pi5-web-navigate',description:'model-catalog-v1'}]};throw Object.assign(Error('Pi RPC command timed out: prompt'),{code:'RPC_TIMEOUT'})}}};const catalog=new PiModelCatalog(worker);assert.equal(catalog.handle({pi5Models:'late',data:{models:[]}}),true);await assert.rejects(catalog.refresh(),{code:'RPC_TIMEOUT'});assert.equal(disposed,true);assert.equal(catalog.pending.size,0);assert.ok(events.some(e=>e.type==='gateway_reconnect'));
});
