const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const { once } = require('node:events');
const { randomUUID } = require('node:crypto');
const { WebSocket } = require('ws');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-tree-'));
process.env.PI_CODING_AGENT_DIR = path.join(root, 'agent'); process.env.PI_PROJECT_ROOTS = root;
process.env.PI_WEB_DEFERRED_FILE = path.join(root, 'deferred.json'); process.env.PI_OFFLINE = '1'; process.env.PI_WEB_TOKEN = 'tree-fixture';
const { sessionTree, revisionOf, checkNavigation } = require('../server/pi-session-tree');
const { searchHistory, previewHistory } = require('../server/pi-history-model');
const u = text => ({ role: 'user', content: text, timestamp: Date.now() });
const a = text => ({ role: 'assistant', content: [{ type: 'text', text }], timestamp: Date.now(), stopReason: 'stop', provider: 'fixture', model: 'fixture', api: 'openai-completions', usage: { input: 10, output: 3, cacheRead: 0, cacheWrite: 0, totalTokens: 13, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } } });
const wait = async predicate => { const until = Date.now() + 15000; while (!await predicate()) { if (Date.now() > until) throw Error('Timed out waiting for native state'); await new Promise(r => setTimeout(r, 20)); } };
test.after(() => fs.rmSync(root, { recursive: true, force: true }));
test('readable search omits tool-only assistant entries, mixed body excludes args, tools remain searchable', async () => {
    const { SessionManager } = await import('@earendil-works/pi-coding-agent'); const sm = SessionManager.inMemory(root);
    sm.appendMessage(u('需求')); const toolCall = { type: 'toolCall', id: 'call1', name: 'read', arguments: { path: 'only-in-args.js', limit: 300 } };
    const pure = sm.appendMessage({ ...a(''), content: [toolCall], stopReason: 'toolUse' });
    const mixed = sm.appendMessage({ ...a('有效结论'), content: [...a('有效结论').content, toolCall] });
    const rows = searchHistory(sm, { filter: 'assistant' }).results;
    assert.deepEqual(rows.map(r => r.entryId), [mixed]); assert.equal(rows[0].snippet, '有效结论');
    assert.equal(searchHistory(sm, { filter: 'assistant', q: 'only-in-args' }).total, 0);
    assert.equal(searchHistory(sm, { filter: 'tool', q: 'only-in-args' }).total, 2);
    assert.equal(searchHistory(sm, { filter: 'conversation' }).total, 2);
    assert.equal(previewHistory(sm, { entryId: mixed }).text, '有效结论');
    assert.match(previewHistory(sm, { entryId: mixed, view: 'record' }).text, /only-in-args/);
    assert.equal(previewHistory(sm, { entryId: pure }).kind, 'tool');
    assert.throws(() => checkNavigation(sm, { entryId: pure, expectedLeafId: sm.getLeafId(), revision: revisionOf(sm), summarize: false }), /执行中的记录/);
    assert.throws(() => checkNavigation(sm, { entryId: mixed, expectedLeafId: sm.getLeafId(), revision: revisionOf(sm), summarize: false }), /执行中的记录/);
});
test('native tree preserves branches, filters private/tool nodes, folds, locates current and rejects stale navigation', async () => {
    const { SessionManager } = await import('@earendil-works/pi-coding-agent'); const sm = SessionManager.inMemory(root);
    const first = sm.appendMessage(u('起点')); const fork = sm.appendMessage(a('共同结论'));
    const abandoned = sm.appendMessage(u('路线 A')); sm.appendMessage(a('A 的结果'));
    sm.branch(fork); const currentUser = sm.appendMessage(u('路线 B'));
    sm.appendCustomEntry('private', { text: 'PRIVATE_PAYLOAD' });
    sm.appendMessage({ ...a(''), content: [{ type: 'toolCall', name: 'read', id: 'tool1', arguments: { path: 'PRIVATE_TOOL_PATH' } }] });
    const leaf = sm.appendMessage(a('B 的结果')); sm.appendLabelChange(leaf, '已验证');
    const before = JSON.stringify(sm.getEntries()), tree = sessionTree(sm, { focus: 'current' });
    assert.equal(tree.currentId, leaf); assert.equal(tree.rows.find(r => r.entryId === abandoned).parentId, fork);
    assert.equal(tree.rows.find(r => r.entryId === leaf).parentId, currentUser);
    assert.equal(tree.rows.find(r => r.entryId === fork).childCount, 2);
    assert.equal(tree.rows.find(r => r.entryId === abandoned).inCurrentBranch, false);
    assert.doesNotMatch(JSON.stringify(tree), /PRIVATE_PAYLOAD|PRIVATE_TOOL_PATH/);
    assert.equal(sessionTree(sm, { collapsed: [fork] }).rows.length, 2);
    assert.equal(sessionTree(sm, { collapsed: [fork], focus: 'current' }).rows.length, tree.rows.length);
    assert.equal(JSON.stringify(sm.getEntries()), before);
    const input = { entryId: first, expectedLeafId: tree.leafId, revision: tree.revision, summarize: false };
    assert.equal(checkNavigation(sm, input).id, first);
    sm.appendLabelChange(leaf, '新书签'); assert.throws(() => checkNavigation(sm, input), /更新/);
    for (let i = 0; i < 260; i++) sm.appendMessage(u(`item ${i}`));
    const page = sessionTree(sm, { focus: 'current' }); assert.ok(page.offset >= 200); assert.ok(page.rows.some(r => r.current));
    assert.throws(() => sessionTree(sm, { offset: 100, revision: tree.revision }), /更新/);
});
test('tree reply stages use native successors and settled state, independent of folding and pagination', async () => {
    const { SessionManager } = await import('@earendil-works/pi-coding-agent'); const sm = SessionManager.inMemory(root);
    sm.appendMessage({ ...u('Question 1'), timestamp: 0 });
    const progress = sm.appendMessage(a('A textual progress update with stop reason stop'));
    const hiddenTool = sm.appendMessage({ ...a(''), content: [{ type: 'toolCall', id: 'c', name: 'read', arguments: {} }], stopReason: 'toolUse' });
    sm.appendMessage({ role: 'toolResult', toolCallId: 'c', content: [{ type: 'text', text: 'tool evidence' }], timestamp: Date.now() });
    const final = sm.appendMessage(a('Completed first answer'));
    sm.appendMessage(u('Question 2'));
    const tail = sm.appendMessage(a('Tail answer'));
    sm.appendLabelChange(tail, 'bookmark metadata');
    const rows = options => sessionTree(sm, {}, options).rows;
    assert.equal(rows({ settled: false }).find(r => r.entryId === tail).replyStage, 'pending');
    assert.equal(rows({ settled: false }).find(r => r.entryId === final).replyStage, 'final');
    assert.equal(rows({ settled: true }).find(r => r.entryId === tail).replyStage, 'final');
    assert.equal(rows({ settled: true }).find(r => r.entryId === progress).replyStage, 'progress');
    assert.ok(!rows({ settled: true }).some(r => r.entryId === hiddenTool));
    assert.equal(rows({ settled: true })[0].timestamp, 0, 'valid epoch timestamp is not replaced');
    // A node with an assistant continuation on any branch must not be labelled final.
    sm.branch(final); sm.appendMessage(a('Continuation on another path'));
    assert.equal(rows({ settled: true }).find(r => r.entryId === final).replyStage, 'progress');
    const stopped = sm.appendMessage({ ...a('Stopped'), stopReason: 'aborted' });
    const failed = sm.appendMessage({ ...a('Failed'), stopReason: 'error' });
    const legacy = sm.appendMessage({ ...a('Old record without terminal information'), stopReason: undefined });
    assert.equal(rows({ settled: true }).find(r => r.entryId === stopped).replyStage, 'stopped');
    assert.equal(rows({ settled: true }).find(r => r.entryId === failed).replyStage, 'error');
    assert.equal(rows({ settled: true }).find(r => r.entryId === legacy).replyStage, 'unknown');
    const boundary = sm.appendMessage(a('Before compaction'));
    sm.appendCompaction('summary', boundary, 5000);
    assert.equal(rows({ settled: true }).find(r => r.entryId === boundary).replyStage, 'unknown');
    for (let i = 0; i < 120; i++) sm.appendMessage(u(`later question ${i}`));
    const folded = sessionTree(sm, { collapsed: [progress] }, { settled: true });
    assert.equal(folded.rows.find(r => r.entryId === progress).replyStage, 'progress');
    assert.equal(sessionTree(sm, {}, { settled: true }).rows.find(r => r.entryId === progress).replyStage, 'progress');
});
test('actual RPC navigation: no new worker/history, draft images, native summary, cancellation, stale clients and durable leaf', { timeout: 90000 }, async t => {
    let mode = 'normal', held; const requests = [], sockets = [];
    const provider = http.createServer(async (req, res) => {
        let raw = ''; for await (const chunk of req) raw += chunk; requests.push(JSON.parse(raw));
        if (mode === 'hold') { held = res; return; }
        if (mode === 'error') { res.writeHead(400, { 'Content-Type': 'application/json' }); res.end(JSON.stringify({ error: { message: 'fixture summary failure' } })); return; }
        res.writeHead(200, { 'Content-Type': 'text/event-stream' });
        for (const chunk of [{ choices: [{ index: 0, delta: { role: 'assistant', content: '## 已探索\n路线 A 的限制需要保留。' }, finish_reason: null }] }, { choices: [{ index: 0, delta: {}, finish_reason: 'stop' }], usage: { prompt_tokens: 80, completion_tokens: 12, total_tokens: 92 } }]) res.write(`data: ${JSON.stringify({ id: 'fixture', object: 'chat.completion.chunk', model: 'fixture', ...chunk })}\n\n`);
        res.end('data: [DONE]\n\n');
    });
    provider.listen(0, '127.0.0.1'); await once(provider, 'listening');
    fs.mkdirSync(process.env.PI_CODING_AGENT_DIR, { recursive: true });
    fs.writeFileSync(path.join(process.env.PI_CODING_AGENT_DIR, 'models.json'), JSON.stringify({ providers: { fixture: { baseUrl: `http://127.0.0.1:${provider.address().port}/v1`, api: 'openai-completions', apiKey: 'fixture', models: [{ id: 'fixture', input: ['text', 'image'], contextWindow: 32000, maxTokens: 1000 }] } } }));
    fs.writeFileSync(path.join(process.env.PI_CODING_AGENT_DIR, 'settings.json'), JSON.stringify({ defaultProvider: 'fixture', defaultModel: 'fixture', compaction: { enabled: false }, retry: { enabled: false } }));
    fs.mkdirSync(path.join(process.env.PI_CODING_AGENT_DIR, 'extensions'));
    fs.writeFileSync(path.join(process.env.PI_CODING_AGENT_DIR, 'extensions/guard.ts'), `export default function(pi) { pi.on('session_before_tree', (event,ctx) => { if(ctx.sessionManager.getLabel(event.preparation.targetId)==='cancel') return {cancel:true}; }); }`);
    const { createPiAgentGateway } = require('../server/pi-agent-routes'); const gateway = createPiAgentGateway();
    const app = require('express')(); app.use(require('express').json()); gateway.mount(app); const server = app.listen(0, '127.0.0.1'); await once(server, 'listening'); gateway.attachWebSocket(server);
    t.after(async () => { sockets.forEach(ws => ws.terminate()); held?.destroy(); await gateway.dispose(); provider.closeAllConnections(); server.closeAllConnections(); await Promise.all([new Promise(r => server.close(r)), new Promise(r => provider.close(r))]); });
    const session = await gateway.store.createSession(root, 'Tree fixture'); const { SessionManager } = await import('@earendil-works/pi-coding-agent'); const sm = SessionManager.open(session.path);
    const image = { type: 'image', mimeType: 'image/png', data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5V8AAAAASUVORK5CYII=' };
    const first = sm.appendMessage({ ...u('first'), content: [{ type: 'text', text: 'First question' }, image] }); const common = sm.appendMessage(a('Common reply'));
    const oldUser = sm.appendMessage(u('Old approach A')); const oldReply = sm.appendMessage(a('Old A result'));
    sm.branch(common); const newUser = sm.appendMessage(u('New approach B')); const newReply = sm.appendMessage(a('New B result')); sm.appendLabelChange(oldUser, 'cancel');
    const connect = async () => {
        const ws = new WebSocket(`ws://127.0.0.1:${server.address().port}/api/pi/ws`); sockets.push(ws); await once(ws, 'open'); const events = [], pending = new Map(); let n = 0;
        ws.on('message', raw => { const e = JSON.parse(raw), p = e.type === 'response' && pending.get(e.id); if (p) { clearTimeout(p.timer); pending.delete(e.id); e.success ? p.resolve(e.data) : p.reject(Error(e.error)); } else events.push(e); });
        const call = (type, input = {}) => new Promise((resolve, reject) => { const id = String(++n), timer = setTimeout(() => { pending.delete(id); reject(Error('timeout ' + type)); }, 40000); pending.set(id, { resolve, reject, timer }); ws.send(JSON.stringify({ id, type, ...input })); });
        await call('open_session', { cwd: root, sessionId: session.id, token: 'tree-fixture' }); return { call, events, ws };
    };
    const one = await connect(), two = await connect(); const worker = gateway.supervisor.getActiveWorker(session.path);
    const input = async (id, summarize = false) => { const p = await one.call('get_history_entry', { entryId: id }); return { entryId: id, expectedLeafId: p.leafId, revision: p.revision, summarize }; };
    const baseline = fs.readFileSync(session.path, 'utf8'); await one.call('get_session_tree', { focus: 'current' }); assert.equal(fs.readFileSync(session.path, 'utf8'), baseline); assert.equal(requests.length, 0);
    const stale = await input(newReply); const changed = await one.call('navigate_history', await input(oldReply)); assert.equal(changed.cancelled, false); assert.equal(changed.draft, null);
    assert.match(JSON.stringify(await two.call('get_messages')), /Old A result/); assert.doesNotMatch(JSON.stringify(await two.call('get_messages')), /New B result/);
    assert.ok(two.events.some(e => e.type === 'gateway_navigation' && e.navigation.job.status === 'done')); assert.ok(two.events.some(e => e.type === 'gateway_context_changed'));
    await assert.rejects(two.call('navigate_history', stale), /更新/);
    const cancelLeaf = (await one.call('get_session_tree')).leafId; assert.equal((await one.call('navigate_history', await input(oldUser))).cancelled, true); assert.equal((await one.call('get_session_tree')).leafId, cancelLeaf);
    gateway.deferred.create(session, { id: randomUUID(), dueAt: Date.now() + 600000, message: 'scheduled message' });
    const drafted = await one.call('navigate_history', await input(first)); assert.deepEqual(drafted.draft, { message: 'First question', images: [image] }); assert.equal((await one.call('get_messages')).messages.length, 0);
    assert.equal(gateway.deferred.jobs[0].status, 'paused'); assert.equal(requests.length, 0);
    await one.call('navigate_history', await input(oldReply));
    await one.call('navigate_history', { ...await input(newReply, true), customInstructions: '保留限制' });
    assert.equal(requests.length, 1); const summaryRequest = JSON.stringify(requests[0]); assert.match(summaryRequest, /Old A result/); assert.doesNotMatch(summaryRequest, /New B result/);
    const messages = (await one.call('get_messages')).messages; assert.ok(messages.some(m => m.role === 'branchSummary')); assert.match(JSON.stringify(messages), /New B result/);
    assert.equal(gateway.supervisor.workers.size, 1);
    let entries = (await worker.request('get_entries')).entries; assert.equal(entries.filter(e => e.type === 'branch_summary').length, 1); assert.ok(entries.some(e => e.id === oldReply));
    mode = 'error'; const failureLeaf = (await one.call('get_session_tree')).leafId;
    await assert.rejects(one.call('navigate_history', await input(common, true)), /fixture summary failure/); assert.equal((await one.call('get_session_tree')).leafId, failureLeaf);
    mode = 'hold'; const navigation = one.call('navigate_history', await input(common, true)); await wait(() => held);
    const nav = (await two.call('get_state')).webNavigation; assert.equal(nav.busy, true);
    assert.equal(gateway.supervisor.getActivity().find(r => r.sessionId === session.id).busy, true, 'summary navigation participates in idle deployment checks');
    await assert.rejects(two.call('prompt', { message: 'must not run' }), /操作/);
    await assert.rejects(two.call('cancel_history_navigation', { navigationId: 'wrong' }), /结束/);
    assert.equal(worker.canEvict(Date.now() + 100000, 1), false);
    await two.call('cancel_history_navigation', { navigationId: nav.job.id }); assert.equal((await navigation).cancelled, true); assert.equal((await one.call('get_session_tree')).leafId, failureLeaf);
    assert.equal((await one.call('get_state')).webNavigation.busy, false);
    await one.call('navigate_history', await input(oldReply));
    const restored = (await one.call('get_messages')).messages;
    worker._handleEvent({ type: 'extension_ui_request', method: 'notify', message: JSON.stringify({ pi5Navigation: 'unknown', data: { secret: 'PRIVATE_LATE' } }) });
    assert.ok(!one.events.some(e => JSON.stringify(e).includes('PRIVATE_LATE')));
    one.ws.close(); two.ws.close(); await gateway.supervisor.stopSession(session.path);
    const reopened = await gateway.supervisor.getWorker({ cwd: root, sessionId: session.id, sessionPath: session.path });
    assert.deepEqual((await reopened.request('get_messages')).messages, restored);
    assert.equal(gateway.supervisor.workers.size, 1);
    entries = (await reopened.request('get_entries')).entries; assert.ok(entries.some(e => e.id === newUser)); assert.ok(entries.some(e => e.id === oldReply));
});
