const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const express = require('express');
const { once } = require('node:events');
const { randomUUID } = require('node:crypto');
const { WebSocket } = require('ws');

const root = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-workflows-'));
process.env.PI_CODING_AGENT_DIR = path.join(root, 'agent');
process.env.PI_PROJECT_ROOTS = root;
process.env.PI_WEB_DEFERRED_FILE = path.join(root, 'deferred.json');
process.env.PI_OFFLINE = '1';
process.env.PI_WEB_TOKEN = 'workflow-test-token';
const { createPiAgentGateway } = require('../server/pi-agent-routes');

const waitFor = async check => {
    const deadline = Date.now() + 10000;
    while (!await check()) { if (Date.now() > deadline) throw new Error('Timed out'); await new Promise(resolve => setTimeout(resolve, 30)); }
};

test('only completed textual replies are eligible for reply-end forks', () => {
    const { isReplyForkPoint } = require('../server/pi-message-payload');
    const entry = { type: 'message', message: { role: 'assistant', content: [{ type: 'text', text: 'Answer' }], stopReason: 'stop' } };
    assert.equal(isReplyForkPoint(entry), true);
    for (const stopReason of ['toolUse', 'pending', 'aborted', 'error']) assert.equal(isReplyForkPoint({ ...entry, message: { ...entry.message, stopReason } }), false);
    assert.equal(isReplyForkPoint({ ...entry, message: { ...entry.message, content: [...entry.message.content, { type: 'toolCall', id: 'pending', name: 'read', arguments: {} }] } }), false);
    assert.equal(isReplyForkPoint({ ...entry, message: { ...entry.message, content: [{ type: 'thinking', thinking: 'Internal only' }] } }), false);
    assert.equal(isReplyForkPoint({ ...entry, message: { ...entry.message, role: 'user' } }), false);
    assert.equal(isReplyForkPoint(null), false);
});

test('native session workflows preserve original forks, retry context, versions, attachments and exclusivity', { timeout: 90000 }, async t => {
    const requests = [];
    const provider = http.createServer(async (req, res) => {
        let raw = ''; for await (const part of req) raw += part;
        requests.push(JSON.parse(raw));
        res.writeHead(200, { 'Content-Type': 'text/event-stream' });
        res.write(`data: ${JSON.stringify({ id: 'fixture', object: 'chat.completion.chunk', model: 'fixture', choices: [{ index: 0, delta: { role: 'assistant', content: 'New branch reply' }, finish_reason: null }] })}\n\n`);
        res.end(`data: ${JSON.stringify({ id: 'fixture', object: 'chat.completion.chunk', model: 'fixture', choices: [{ index: 0, delta: {}, finish_reason: 'stop' }], usage: { prompt_tokens: 100, completion_tokens: 10, total_tokens: 110 } })}\n\ndata: [DONE]\n\n`);
    });
    provider.listen(0, '127.0.0.1'); await once(provider, 'listening');
    fs.mkdirSync(process.env.PI_CODING_AGENT_DIR, { recursive: true });
    fs.writeFileSync(path.join(process.env.PI_CODING_AGENT_DIR, 'models.json'), JSON.stringify({ providers: { fixture: {
        baseUrl: `http://127.0.0.1:${provider.address().port}/v1`, api: 'openai-completions', apiKey: 'fixture', models: [{ id: 'fixture', name: 'Fixture', input: ['text', 'image'], reasoning: false, contextWindow: 32000, maxTokens: 1000, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 } }]
    } } }));
    fs.writeFileSync(path.join(process.env.PI_CODING_AGENT_DIR, 'settings.json'), JSON.stringify({ defaultProvider: 'fixture', defaultModel: 'fixture', compaction: { enabled: false } }));
    const gateway = createPiAgentGateway();
    const app = express(); app.use(express.json({ limit: '25mb' })); gateway.mount(app);
    const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
    const wss = gateway.attachWebSocket(server);
    t.after(async () => {
        for (const ws of wss.clients) ws.terminate();
        await gateway.dispose();
        provider.closeAllConnections();
        await Promise.all([new Promise(resolve => server.close(resolve)), new Promise(resolve => provider.close(resolve))]);
        fs.rmSync(root, { recursive: true, force: true });
    });
    const base = `http://127.0.0.1:${server.address().port}/api/pi`;
    const api = async (tail, body, method = 'POST') => {
        const response = await fetch(`${base}${tail}`, { method: body ? method : 'GET', headers: { Authorization: 'Bearer workflow-test-token', 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify({ cwd: root, ...body }) } : {}) });
        return { status: response.status, data: await response.json() };
    };
    assert.equal((await fetch(`${base}/sessions/x/workflow?cwd=${root}`)).status, 401);
    const session = await gateway.store.createSession(root, 'Original');
    const prefix = `/sessions/${session.id}`;
    const { SessionManager } = await import('@earendil-works/pi-coding-agent');
    const manager = SessionManager.open(session.path);
    manager.appendModelChange('fixture', 'fixture');
    const image = { type: 'image', mimeType: 'image/png', data: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5V8AAAAASUVORK5CYII=' };
    const first = manager.appendMessage({ role: 'user', content: [{ type: 'text', text: 'First question' }, image], timestamp: 1 });
    const assistant = (text, timestamp) => ({ role: 'assistant', content: [{ type: 'text', text }], api: 'openai-completions', provider: 'fixture', model: 'fixture', stopReason: 'stop', timestamp, usage: { input: 1, output: 1, cacheRead: 0, cacheWrite: 0, totalTokens: 2, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } } });
    const firstReply = manager.appendMessage(assistant('First reply', 2));
    const last = manager.appendMessage({ role: 'user', content: 'Old question', timestamp: 3 });
    manager.appendMessage(assistant('Old unwanted reply', 4));
    manager.appendCompaction('Old unwanted reply summarized', last, 1000);
    const view = await api(`${prefix}/workflow?cwd=${encodeURIComponent(root)}`);
    const oldLeafId = view.data.leafId;
    const bytesBefore = fs.readFileSync(session.path);
    assert.equal(view.data.lastUserId, last);
    const worker = gateway.supervisor.getActiveWorker(session.path);
    assert.ok(worker);
    const clients = [];
    const clientEvents = [[], []];
    for (let index = 0; index < 2; index++) {
        const ws = new WebSocket(`${base.replace('http:', 'ws:')}/ws`);
        await once(ws, 'open');
        ws.on('message', raw => clientEvents[index].push(JSON.parse(raw)));
        ws.send(JSON.stringify({ id: 'open', type: 'open_session', token: 'workflow-test-token', cwd: root, sessionId: session.id }));
        await waitFor(() => clientEvents[index].some(event => event.command === 'open_session'));
        clients.push(ws);
    }
    assert.equal(worker.subscribers.size, 2);
    assert.ok(!(await worker.request('get_commands')).commands.some(command => command.name.includes('pi5-web-navigate')));
    assert.equal((await api(`${prefix}/fork`, { expectedLeafId: 'stale' })).status, 400);
    const clone = await api(`${prefix}/fork`, { expectedLeafId: oldLeafId });
    assert.equal(clone.status, 201, JSON.stringify(clone));
    assert.notEqual(clone.data.session.id, session.id);
    assert.deepEqual(SessionManager.open(clone.data.session.path).buildSessionContext().messages, manager.buildSessionContext().messages);
    assert.equal(gateway.supervisor.getActiveWorker(session.path), worker);
    assert.ok(view.data.replies.some(reply => reply.entryId === firstReply && reply.text === 'First reply'));
    const afterReply = await api(`${prefix}/fork`, { entryId: firstReply, position: 'at', expectedLeafId: oldLeafId });
    assert.equal(afterReply.status, 201, JSON.stringify(afterReply));
    assert.equal(afterReply.data.draft, null);
    const replyContext = SessionManager.open(afterReply.data.session.path).buildSessionContext().messages;
    assert.equal(replyContext.length, 2);
    assert.ok(JSON.stringify(replyContext).includes('First reply'));
    assert.ok(!JSON.stringify(replyContext).includes('Old question'));
    assert.deepEqual(replyContext[0].content, [{ type: 'text', text: 'First question' }, image]);
    for (const input of [{ entryId: first, position: 'at' }, { position: 'at' }, { entryId: firstReply, position: 'after' }, { entryId: 'missing', position: 'at' }, { entryId: firstReply }]) {
        assert.equal((await api(`${prefix}/fork`, { ...input, expectedLeafId: oldLeafId })).status, 400);
    }
    const fork = await api(`${prefix}/fork`, { entryId: last, expectedLeafId: oldLeafId });
    assert.equal(fork.status, 201);
    assert.equal(fork.data.draft.message, 'Old question');
    assert.equal(SessionManager.open(fork.data.session.path).buildSessionContext().messages.length, 2);
    const fromFirst = await api(`${prefix}/fork`, { entryId: first, expectedLeafId: oldLeafId });
    assert.equal(fromFirst.status, 201);
    assert.deepEqual(fromFirst.data.draft.images, [image]);
    assert.ok(fs.existsSync(fromFirst.data.session.path), 'empty fork is immediately visible');
    assert.equal(SessionManager.open(fromFirst.data.session.path).buildSessionContext().messages.length, 0);
    assert.deepEqual(fs.readFileSync(session.path), bytesBefore);
    assert.equal(requests.length, 0, 'fork and listing do not call a model');
    assert.equal((await api(`${prefix}/retry`, { entryId: first, expectedLeafId: oldLeafId, message: 'Cannot edit old question' })).status, 400);
    const scheduled = await api(`${prefix}/deferred`, { id: randomUUID(), message: 'Deferred original', dueAt: Date.now() + 600000 });
    assert.equal(scheduled.status, 201);
    assert.equal(gateway.deferred.list(root, clone.data.session.id).length, 0, 'fork does not inherit delayed messages');
    const retried = await api(`${prefix}/retry`, { entryId: last, expectedLeafId: oldLeafId, message: 'Replacement question', images: [image] });
    assert.equal(retried.status, 200, JSON.stringify(retried));
    await waitFor(async () => !(await worker.request('get_state')).isStreaming);
    await waitFor(() => requests.length === 1);
    const outgoing = JSON.stringify(requests[0].messages);
    assert.ok(outgoing.includes('First question'));
    assert.ok(outgoing.includes('Replacement question'));
    assert.ok(!outgoing.includes('Old unwanted reply'));
    assert.ok(!outgoing.includes('Old question'));
    assert.ok(!outgoing.includes('pi5-web-navigate'));
    assert.equal(gateway.deferred.jobs[0].status, 'paused');
    await waitFor(() => clientEvents.every(events => events.some(event => event.type === 'gateway_context_changed')));
    assert.equal(worker.subscribers.size, 2);
    assert.ok(clientEvents.every(events => events.some(event => event.type === 'gateway_context_changed' && !JSON.stringify(event.messages).includes('Old unwanted reply'))));
    clients.forEach(ws => ws.close());
    await waitFor(() => worker.subscribers.size === 0);
    const entries = (await worker.request('get_entries')).entries;
    assert.ok(entries.some(entry => entry.message?.content?.[0]?.text === 'Old unwanted reply'));
    assert.ok(!entries.some(entry => entry.type === 'branch_summary'));
    const current = (await api(`${prefix}/workflow?cwd=${encodeURIComponent(root)}`)).data;
    assert.ok(current.versions.some(version => version.entryId === oldLeafId));
    const restored = await api(`${prefix}/restore`, { entryId: oldLeafId, expectedLeafId: current.leafId });
    assert.equal(restored.status, 200, JSON.stringify(restored));
    const restoredMessages = JSON.stringify((await worker.request('get_messages')).messages);
    assert.ok(restoredMessages.includes('Old unwanted reply'));
    assert.ok(!restoredMessages.includes('New branch reply'));
    await gateway.supervisor.stopSession(session.path);
    const reopened = await gateway.supervisor.getWorker({ cwd: root, sessionId: session.id, sessionPath: session.path });
    assert.ok(JSON.stringify((await reopened.request('get_messages')).messages).includes('Old unwanted reply'), 'restored leaf survives restart');
    let unlock;
    const locked = reopened.exclusive(async () => new Promise(resolve => { unlock = resolve; }));
    await waitFor(() => unlock);
    await assert.rejects(reopened.request('prompt', { message: 'Must not race' }), /操作进行中/);
    await assert.rejects(reopened.exclusive(() => {}), /会话正在/);
    assert.equal(reopened.canEvict(Date.now() + 9999999, 1), false);
    unlock(); await locked;
    const originalRequest = reopened.client.request.bind(reopened.client);
    reopened.client.request = (type, ...args) => type === 'get_commands' ? Promise.resolve({ commands: [] }) : originalRequest(type, ...args);
    await assert.rejects(reopened.exclusive(rpc => reopened.navigate(rpc, { mode: 'retry', entryId: last })), /扩展未加载/);
    reopened.client.request = originalRequest;
    assert.equal(requests.length, 1, 'missing control extension never falls through to a model prompt');
    assert.equal((await api(`${prefix}/deferred?cwd=/etc`)).status, 400);
    assert.equal(requests.length, 1);
    const delayedId = randomUUID();
    const delayedPrefix = `/sessions/${fromFirst.data.session.id}`;
    const delayed = await api(`${delayedPrefix}/deferred`, { id: delayedId, message: 'Headless delayed message', dueAt: Date.now() + 60000 });
    assert.equal(delayed.status, 201);
    assert.equal((await api(`${delayedPrefix}/deferred/${delayedId}`, { action: 'send', revision: 1 }, 'PATCH')).status, 200);
    await gateway.deferred.tick();
    await waitFor(() => requests.length === 2);
    await gateway.deferred.tick();
    assert.equal(requests.length, 2, 'headless real RPC handoff is not repeated');
    assert.equal(gateway.deferred.jobs.find(job => job.id === delayedId).status, 'sent');
    assert.ok(JSON.stringify(requests[1]).includes('Headless delayed message'));
    const delayedWorker = gateway.supervisor.getActiveWorker(fromFirst.data.session.path);
    assert.equal(delayedWorker.subscribers.size, 0);
    await waitFor(async () => !(await delayedWorker.request('get_state')).isStreaming);
    const cancelled = await api(`${prefix}?cwd=${encodeURIComponent(root)}`, { cwd: root }, 'DELETE');
    assert.equal(cancelled.status, 200, JSON.stringify(cancelled));
    assert.equal(gateway.deferred.jobs[0].status, 'cancelled');
});
