const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const { once } = require('node:events');
const root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'pi-transfer-test-')));
process.env.PI_CODING_AGENT_DIR = path.join(root, 'agent');
process.env.PI_PROJECT_ROOTS = root;
process.env.PI_WEB_DEFERRED_FILE = path.join(root, 'deferred.json');
process.env.PI_OFFLINE = '1'; process.env.PI_WEB_TOKEN = 'transfer-test';
const { PiSessionStore } = require('../server/pi-session-store');
const { PiSessionTransfer, validateImport } = require('../server/pi-session-transfer');
const assistant = value => ({ role: 'assistant', content: [{ type: 'text', text: value }], timestamp: Date.now(), stopReason: 'stop', provider: 'fixture', model: 'fixture', api: 'openai-completions', usage: { input: 10, output: 3, cacheRead: 0, cacheWrite: 0, totalTokens: 13, cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 } } });
const user = content => ({ role: 'user', content, timestamp: Date.now() });
const jsonl = entries => entries.map(e => JSON.stringify(e)).join('\n') + '\n';
test.after(() => fs.rmSync(root, { recursive: true, force: true }));

test('native JSONL import creates independent identities and cwd, retains tree/labels/images/compaction and never starts a worker', async () => {
    const { SessionManager } = await import('@earendil-works/pi-coding-agent');
    const store = new PiSessionStore();
    const target = path.join(root, '目标项目'); fs.mkdirSync(target);
    const original = await store.createSession(root, 'Original');
    const sm = SessionManager.open(original.path);
    const first = sm.appendMessage(user('中文\u2028\u2029 history'));
    const fork = sm.appendMessage(assistant('first reply'));
    sm.appendMessage(user('other branch')); sm.appendMessage(assistant('abandoned evidence'));
    sm.branch(fork);
    const retained = sm.appendMessage(user([{ type: 'image', mimeType: 'image/png', data: 'aGVsbG8=' }, { type: 'text', text: '图片' }]));
    sm.appendMessage(assistant('current branch')); sm.appendCompaction('已有摘要', retained, 40000);
    sm.appendLabelChange(first, 'bookmark'); sm.appendSessionInfo('导入名称');
    const content = fs.readFileSync(original.path, 'utf8');
    const transfer = new PiSessionTransfer({ store, supervisor: { getWorker() { throw Error('must not start'); } } });
    const a = await transfer.import(target, content, 'same-import-request-0001');
    const duplicate = await transfer.import(target, content, 'same-import-request-0001');
    assert.equal(duplicate.session.id, a.session.id);
    assert.doesNotMatch(JSON.stringify([...transfer.imports.values()]), /firstMessage|中文|导入名称/);
    const b = await transfer.import(target, content, 'new-import-request-00002');
    assert.notEqual(a.session.id, original.id); assert.notEqual(a.session.id, b.session.id);
    assert.equal(a.session.cwd, target); assert.equal(a.session.name, '导入名称');
    const imported = SessionManager.open(a.session.path);
    assert.deepEqual(imported.getEntries(), JSON.parse(JSON.stringify(sm.getEntries()))); assert.equal(imported.getLabel(first), 'bookmark');
    assert.equal(imported.getHeader().cwd, target); assert.equal(fs.existsSync(imported.getHeader().parentSession), false, 'uploaded source is cleaned'); require('./private-file-helper.cjs').assertPrivateFile(a.session.path);
    assert.equal(fs.readFileSync(original.path, 'utf8'), content);
    assert.equal((await store.listSessions(target)).length, 2);
    await assert.rejects(transfer.import(root, content, 'same-import-request-0001'), /另一个/);
    await assert.rejects(transfer.import(path.dirname(root), content, 'bad-import-request-0001'), /outside/);
    const empty = await store.createSession(root, 'empty source');
    const emptyCopy = await transfer.import(target, fs.readFileSync(empty.path, 'utf8'), 'empty-import-request-0001');
    assert.equal(emptyCopy.session.messageCount, 0); assert.ok(fs.existsSync(emptyCopy.session.path));
    const legacy = JSON.parse(JSON.stringify(sm.getEntries()));
    const legacyCopy = await transfer.import(target, jsonl([{ ...sm.getHeader(), version: 2, cwd: '/missing/original' }, ...legacy]), 'legacy-import-request-0001');
    assert.equal(SessionManager.open(legacyCopy.session.path).getHeader().version, 3);
});

test('strict import rejects malformed lines, foreign logs, trees with cycles/duplicates, oversized and invalid records', async () => {
    const { SessionManager } = await import('@earendil-works/pi-coding-agent');
    const sm = SessionManager.inMemory(root); sm.appendMessage(user('question')); sm.appendMessage(assistant('reply'));
    const valid = [sm.getHeader(), ...sm.getEntries()];
    const system = { type: 'message', id: 'system-entry', parentId: null, timestamp: new Date().toISOString(), message: {
        role: 'system', content: '', sections: { preamble: 'Fixture prompt', tools: null },
        toolsAdded: [{ name: 'read', description: 'Read files', parameters: { type: 'object', properties: {} } }],
        toolsRemoved: [{ name: 'old-tool' }], timestamp: Date.now()
    } };
    assert.equal(validateImport('\uFEFF' + jsonl([valid[0], system, ...valid.slice(1)]).replace(/\n/g, '\r\n')).length, 4);
    for (const value of ['', '<html>archive</html>', '{"type":"session_meta"}', jsonl(valid) + '{broken}', 'x'.repeat(16 * 1024 * 1024 + 1)]) assert.throws(() => validateImport(value));
    const bad = change => { const entries = structuredClone(valid); change(entries); assert.throws(() => validateImport(jsonl(entries))); };
    bad(e => e[0].version = 999); bad(e => e[1].parentId = e[1].id); bad(e => e[2].id = e[1].id);
    bad(e => e[2].message.content = null); bad(e => e[2].message.stopReason = 'pending');
    bad(e => e[2].message.usage.cost = 'invalid');
    bad(e => e[2].message.role = 'event_msg'); bad(e => e[1].type = 'unknown');
    const badSystem = change => { const entries = structuredClone([valid[0], { type: 'message', id: 'system-entry', parentId: null, timestamp: new Date().toISOString(), message: { role: 'system', content: '', timestamp: Date.now() } }, ...valid.slice(1)]); change(entries[1].message); assert.throws(() => validateImport(jsonl(entries))); };
    badSystem(message => message.toolsAdded = [{ name: '', description: 'bad', parameters: {} }]);
    badSystem(message => message.sections = { broken: 42 });
    bad(e => e[1].timestamp = 'bad');
});

test('protected HTTP exports actual native HTML tree and current-branch JSONL; import does not switch original worker', { timeout: 90000 }, async t => {
    const { createPiAgentGateway } = require('../server/pi-agent-routes');
    const gateway = createPiAgentGateway({ deferredFilePath: process.env.PI_WEB_DEFERRED_FILE });
    const express = require('express'), app = express(); app.use(express.json({ limit: '32mb' })); gateway.mount(app);
    const server = http.createServer(app); server.listen(0, '127.0.0.1'); await once(server, 'listening');
    t.after(async () => { await gateway.dispose(); server.closeAllConnections(); await new Promise(resolve => server.close(resolve)); });
    const base = `http://127.0.0.1:${server.address().port}/api/pi`;
    const call = (url, body, headers = {}) => fetch(base + url, { method: body ? 'POST' : 'GET', headers: { Authorization: 'Bearer transfer-test', 'Content-Type': 'application/json', ...headers }, body: body ? JSON.stringify(body) : undefined });
    const original = await gateway.store.createSession(root, 'Export fixture');
    const { SessionManager } = await import('@earendil-works/pi-coding-agent'); const sm = SessionManager.open(original.path);
    sm.appendMessage(user('original question')); const fork = sm.appendMessage(assistant('fork point'));
    sm.appendMessage(user('abandoned unique')); sm.appendMessage(assistant('abandoned answer'));
    sm.branch(fork); const retained = sm.appendMessage(user('current unique \u2028\u2029')); sm.appendMessage(assistant('<script>window.BAD=1</script> current answer'));
    sm.appendCompaction('已有压缩摘要', retained, 40000); sm.appendLabelChange(fork, '验证点');
    const worker = await gateway.supervisor.getWorker({ cwd: root, sessionPath: original.path, sessionId: original.id });
    await worker.request('get_state'); const baseline = fs.readFileSync(original.path, 'utf8');
    const count = gateway.supervisor.workers.size;
    assert.equal((await (await call('/status')).json()).sessionTransfer, true);
    const endpoint = `/sessions/${original.id}/export`;
    assert.equal((await call(endpoint, { cwd: root, format: 'html' }, { Authorization: '' })).status, 401);
    assert.equal((await call(endpoint, { cwd: root, format: 'html' }, { Origin: 'http://evil.invalid' })).status, 403);
    assert.equal((await call(endpoint, { cwd: '/etc', format: 'html' })).status, 400);
    const html = await call(endpoint, { cwd: root, format: 'html', outputPath: '/tmp/ignored-user-output.html' });
    assert.equal(html.status, 200); assert.match(html.headers.get('content-disposition'), /attachment/);
    assert.equal(html.headers.get('cache-control'), 'no-store'); assert.equal(html.headers.get('x-content-type-options'), 'nosniff');
    const markup = await html.text(); assert.match(markup, /<!DOCTYPE html>/i);
    const encoded = markup.match(/<script id="session-data" type="application\/json">([^<]+)<\/script>/);
    assert.ok(encoded, 'native export includes embedded session data');
    const data = JSON.parse(Buffer.from(encoded[1], 'base64').toString('utf8'));
    assert.match(JSON.stringify(data.entries), /abandoned unique/); assert.match(JSON.stringify(data.entries), /current unique/);
    assert.ok(data.systemPrompt); assert.ok(data.tools.length);
    const download = await call(endpoint, { cwd: root, format: 'jsonl' }); assert.equal(download.status, 200);
    const content = await download.text(); validateImport(content);
    assert.match(content, /current unique/); assert.doesNotMatch(content, /abandoned unique/);
    assert.ok(content.includes('\u2028\u2029')); assert.equal(fs.readFileSync(original.path, 'utf8'), baseline);
    const imported = await call('/sessions/import', { cwd: root, content, requestId: 'http-import-fixture-0001' }); assert.equal(imported.status, 201);
    const result = await imported.json(); assert.notEqual(result.session.id, original.id);
    assert.equal(gateway.supervisor.workers.size, count); assert.equal(worker.sessionId, original.id);
    assert.equal((await worker.request('get_state')).sessionId, original.id);
    const resumed = await gateway.supervisor.getWorker({ cwd: root, sessionPath: result.session.path, sessionId: result.session.id });
    assert.equal((await resumed.request('get_state')).sessionId, result.session.id);
    assert.match(JSON.stringify(await resumed.request('get_messages')), /current unique/);
    assert.equal((await call('/sessions/import', { cwd: root, content: content + '\nBAD', requestId: 'http-invalid-fixture-0001' })).status, 400);
    const token = Symbol('busy-fixture'); worker.operation = token;
    assert.equal((await call(endpoint, { cwd: root, format: 'html' })).status, 409); worker.operation = null;
    assert.equal(fs.readFileSync(original.path, 'utf8'), baseline);
    fs.writeFileSync(path.join(root, 'pi-transfer-native-fixture.html'), markup);
});
